=== emergentdotorg/gitver-maven-extension/src/main/resources/schema/gitver-configuration-v1.0.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  xmlns="http://emergentdotorg.github.io/gitver/configuration/1.0.0"
  targetNamespace="http://emergentdotorg.github.io/gitver/configuration/1.0.0">

  <xs:element name="configuration" type="Configuration"/>

  <xs:complexType name="Options">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        Options that can be configured at any level.
      </xs:documentation>
    </xs:annotation>
    <xs:all>
      <xs:element name="version" type="xs:string" minOccurs="0"/>
      <xs:element name="tagPattern" type="xs:string" minOccurs="0"/>
      <xs:element name="followFirstParentOnly" type="xs:boolean" minOccurs="0"/>
      <xs:element name="updateAttachedPom" type="xs:boolean" minOccurs="0"/>
      <xs:element name="updateSourcePom" type="xs:boolean" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="Configuration">
    <xs:complexContent mixed="false">
      <xs:extension base="Options">
        <xs:all>

          <xs:element name="disable" type="xs:boolean" minOccurs="0"/>
          <xs:element name="considerTagsOnBranches" type="xs:string" minOccurs="0"/>
          <xs:element name="projectVersionPattern" type="xs:string" minOccurs="0"/>

          <xs:element name="refs" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="ref" type="RefDetail" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
              <xs:attribute name="appendDefaults" type="xs:boolean" default="false"/>
            </xs:complexType>
          </xs:element>

          <xs:element name="relatedProjects" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="project" type="Project" minOccurs="0" maxOccurs="unbounded"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>

        </xs:all>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="RefDetail">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        Git status description with information on how to process a git state, as well as
        information on how to determine if this description is a match against the current state.
      </xs:documentation>
    </xs:annotation>
    <xs:complexContent mixed="false">
      <xs:extension base="Options">
        <xs:all>

          <xs:element name="type">
            <xs:annotation>
              <xs:documentation xml:lang="en">The ref type to match.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="branch"/>
                <xs:enumeration value="commit"/>
                <xs:enumeration value="tag"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>

          <xs:element name="pattern" type="xs:string" minOccurs="0">
            <xs:annotation>
              <xs:documentation xml:lang="en">The ref name matching regex.</xs:documentation>
            </xs:annotation>
          </xs:element>

          <xs:element name="properties" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>

          <xs:element name="userProperties" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>

        </xs:all>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Project">
    <xs:all>
      <xs:element name="groupId" type="xs:string"/>
      <xs:element name="artifactId" type="xs:string"/>
    </xs:all>
  </xs:complexType>

</xs:schema>

=== emergentdotorg/gitver-maven-extension/src/it/multiModuleRevisionProject/.mvn/gitver.config.xml
<configuration
  xmlns="http://emergentdotorg.github.io/gitver/configuration/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://emergentdotorg.github.io/gitver/configuration/1.0.0
                      https://emergentdotorg.github.io/gitver-configuration-v1.0.0.xsd">

  <considerTagsOnBranches>true</considerTagsOnBranches>
  <refs>

    <ref>
      <type>tag</type>
      <pattern><![CDATA[v(?<version>.*)]]></pattern>
      <version>${ref.version}</version>
      <updateSourcePom>true</updateSourcePom>
      <!--
      <properties>
        <revision>${ref.version}</revision>
        <rev1>${ref.version}</rev1>
        <rev2>${version}</rev2>
      </properties>
      -->
    </ref>

    <!--
    <ref>
      <type>branch</type>
      <pattern>(main|master)</pattern>
      <version>${version.release}-${ref}-${version.label}-SNAPSHOT</version>
      <properties>
        <foo>new_new_new</foo>
      </properties>
    </ref>
    -->

    <ref>
      <type>branch</type>
      <!--<pattern>feature/(.+)</pattern>-->
      <pattern>.+</pattern>
      <version>${version.release}-${ref}-SNAPSHOT</version>
      <!--<version>${ref}-SNAPSHOT</version>-->
      <!--
      <properties>
        <revision>${version.release}-${ref}-SNAPSHOT</revision>
        <rev1>${version.release}-${ref}-SNAPSHOT</rev1>
        <rev2>${version}</rev2>
      </properties>
      -->
    </ref>

  </refs>

  <rev>
    <version>${version.release}-${version.label}-SNAPSHOT</version>
    <!--<version>${ref}-SNAPSHOT</version>-->
    <!--
    <properties>
      <revision>${version.release}-${version.label}-SNAPSHOT</revision>
      <rev1>${version.release}-${version.label}-SNAPSHOT</rev1>
      <rev2>${version}</rev2>
    </properties>
    -->
  </rev>

</configuration>

=== emergentdotorg/gitver-maven-extension/src/it/single-with-branch/.mvn/gitver-config.xml
<configuration
  xmlns="http://emergentdotorg.github.io/gitver/configuration/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://emergentdotorg.github.io/gitver/configuration/1.0.0
                      https://emergentdotorg.github.io/gitver-configuration-v1.0.0.xsd">

  <refs>
    <ref>
      <type>tag</type>
      <pattern><![CDATA[v(?<version>.*)]]></pattern>
      <version>${ref.version}</version>
    </ref>
    <ref>
      <type>branch</type>
      <pattern>(main|master|release-.*)</pattern>
      <version>${describe.tag.version.maven}</version>
    </ref>
    <ref>
      <type>branch</type>
      <pattern>.+</pattern>
      <version>${describe.tag.version.next}-${ref.slug}${dirty}-SNAPSHOT</version>
    </ref>
  </refs>

</configuration>

=== emergentdotorg/gitver-maven-extension/src/main/resources/schema/gitver-defaults.xml
<configuration
  xmlns="http://emergentdotorg.github.io/gitver/configuration/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://emergentdotorg.github.io/gitver/configuration/1.0.0
                      https://emergentdotorg.github.io/gitver-configuration-v1.0.0.xsd">

  <!--<disable>false</disable>-->
  <!--<version>${describe.version}</version>-->
  <!--<onlyFollowFirstParent>true</onlyFollowFirstParent>-->
  <!--<considerTagsOnBranches>false</considerTagsOnBranches>-->
  <!--<updateAttached>true</updateAttached>-->
  <!--<updateSource>false</updateSource>-->

  <refs>

    <ref>
      <type>branch</type>
      <pattern>.+</pattern>
      <version>${describe.tag.version.next}</version>
    </ref>

    <ref>
      <type>tag</type>
      <pattern><![CDATA[v(?<version>.*)]]></pattern>
      <version>${ref.version}</version>
    </ref>

  </refs>

  <rev>
    <version>${commit}</version>
  </rev>

</configuration>
