=== emergentdotorg/gitver-maven-extension/gittle-maven-extension/src/main/resources/schema/gittle-configuration-v1.0.0.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           xmlns="https://emergentdotorg.github.io/gittle/configuration/1.0.0"
           targetNamespace="https://emergentdotorg.github.io/gittle/configuration/1.0.0">

  <xs:element name="configuration">
    <xs:complexType>
      <xs:all>
        <xs:element name="disable" type="xs:boolean" minOccurs="0"/>
        <xs:element name="projectVersionPattern" type="xs:string" minOccurs="0"/>
        <xs:element name="describeTagPattern" type="xs:string" minOccurs="0"/>
        <xs:element name="describeTagFirstParent" type="xs:boolean" minOccurs="0"/>
        <xs:element name="updatePom" type="xs:boolean" minOccurs="0"/>
        <xs:element name="useRevision" type="xs:boolean" minOccurs="0"/>

        <xs:element name="refs" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ref" type="RefPatchDescription" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="considerTagsOnBranches" type="xs:boolean"/>
          </xs:complexType>
        </xs:element>

        <xs:element name="rev" type="PatchDescription" minOccurs="0"/>

        <xs:element name="relatedProjects" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="project" type="RelatedProject" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="PatchDescription">
    <xs:all>
      <xs:element name="describeTagPattern" type="xs:string" minOccurs="0"/>
      <xs:element name="describeTagFirstParent" type="xs:boolean" minOccurs="0"/>
      <xs:element name="updatePom" type="xs:boolean" minOccurs="0"/>
      <xs:element name="useRevision" type="xs:boolean" minOccurs="0"/>

      <xs:element name="version" type="xs:string" minOccurs="0"/>
      <xs:element name="properties" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="userProperties" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="RefPatchDescription">
    <xs:all>
      <xs:element name="pattern" type="xs:string" minOccurs="0"/>
      <xs:element name="describeTagPattern" type="xs:string" minOccurs="0"/>
      <xs:element name="describeTagFirstParent" type="xs:boolean" minOccurs="0"/>
      <xs:element name="updatePom" type="xs:boolean" minOccurs="0"/>
      <xs:element name="useRevision" type="xs:boolean" minOccurs="0"/>

      <xs:element name="version" type="xs:string" minOccurs="0"/>
      <xs:element name="properties" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="userProperties" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:any minOccurs="0" maxOccurs="unbounded" processContents="skip"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>

    <xs:attribute name="type" use="required">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="tag"/>
          <xs:enumeration value="branch"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="RelatedProject">
    <xs:all>
      <xs:element name="groupId" type="xs:string"/>
      <xs:element name="artifactId" type="xs:string"/>
    </xs:all>
  </xs:complexType>

</xs:schema>

=== emergentdotorg/gitver-maven-extension/gittle-maven-extension/src/it/multiModuleProject/.mvn/gittle-maven-extension.xml
<configuration xmlns="https://emergentdotorg.github.io/gittle/configuration/1.0.0"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://emergentdotorg.github.io/gittle/configuration/1.0.0
                                   https://emergentdotorg.github.io/gittle-configuration-v1.0.0.xsd">
  <refs>

    <ref type="tag">
      <pattern><![CDATA[v(?<version>.*)]]></pattern>
      <version>${ref.version}</version>
      <updatePom>true</updatePom>
    </ref>

    <ref type="branch">
      <pattern>master</pattern>
      <version>${version.release}-${ref}-${version.label}</version>
      <properties>
        <foo>new_new_new</foo>
      </properties>
    </ref>

    <ref type="branch">
      <pattern>feature/(.+)</pattern>
      <version>${ref}-SNAPSHOT</version>
      <properties>
        <foo>new_new_new</foo>
      </properties>
    </ref>

  </refs>
</configuration>

=== emergentdotorg/gitver-maven-extension/gittle-maven-extension/src/it/standard-qualified-branch/.mvn/gittle.config.xml
<configuration xmlns="http://emergentdotorg.github.io/gittle/configuration/1.0.0"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://emergentdotorg.github.io/gittle/configuration/1.0.0
                                   https://emergentdotorg.github.io/gittle-configuration-v1.0.0.xsd">

  <refs considerTagsOnBranches="false">

    <ref type="tag">
      <pattern><![CDATA[v(?<version>.*)]]></pattern>
      <version>${ref.version}</version>
    </ref>

    <ref type="branch">
      <pattern>(main|master)</pattern>
      <version>${describe.tag.version.next}</version>
    </ref>

    <ref type="branch">
      <pattern>.+</pattern>
      <version>${ref.slug}-${describe.distance}-${commit.short}-SNAPSHOT</version>
    </ref>

  </refs>

</configuration>

=== emergentdotorg/gitver-maven-extension/gittle-maven-extension/src/it/multiModuleRevisionProject/.mvn/gittle-maven-extension.xml
<configuration xmlns="https://emergentdotorg.github.io/gittle/configuration/1.0.0"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="https://emergentdotorg.github.io/gittle/configuration/1.0.0
                                   https://emergentdotorg.github.io/gittle-configuration-v1.0.0.xsd">

  <refs considerTagsOnBranches="true">

    <ref type="tag">
      <pattern><![CDATA[v(?<version>.*)]]></pattern>
      <version>${ref.version}</version>
      <updatePom>true</updatePom>
      <!--
      <properties>
        <revision>${ref.version}</revision>
        <rev1>${ref.version}</rev1>
        <rev2>${version}</rev2>
      </properties>
      -->
    </ref>

    <!--
    <ref type="branch">
      <pattern>(main|master)</pattern>
      <version>${version.release}-${ref}-${version.label}-SNAPSHOT</version>
      <properties>
        <foo>new_new_new</foo>
      </properties>
    </ref>
    -->

    <ref type="branch">
      <!--<pattern>feature/(.+)</pattern>-->
      <pattern>.+</pattern>
      <version>${version.release}-${ref}-SNAPSHOT</version>
      <!--<version>${ref}-SNAPSHOT</version>-->
      <!--
      <properties>
        <revision>${version.release}-${ref}-SNAPSHOT</revision>
        <rev1>${version.release}-${ref}-SNAPSHOT</rev1>
        <rev2>${version}</rev2>
      </properties>
      -->
    </ref>

  </refs>

  <rev>
    <version>${version.release}-${version.label}-SNAPSHOT</version>
    <!--<version>${ref}-SNAPSHOT</version>-->
    <!--
    <properties>
      <revision>${version.release}-${version.label}-SNAPSHOT</revision>
      <rev1>${version.release}-${version.label}-SNAPSHOT</rev1>
      <rev2>${version}</rev2>
    </properties>
    -->
  </rev>

</configuration>

=== emergentdotorg/gitver-maven-extension/gittle-maven-extension/src/main/resources/schema/gittle-defaults.xml
<configuration
  xmlns="https://emergentdotorg.github.io/gittle/configuration/1.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://emergentdotorg.github.io/gittle/configuration/1.0.0
                      https://emergentdotorg.github.io/gittle-configuration-v1.0.0.xsd">

  <refs>

    <ref type="branch">
      <pattern>.+</pattern>
      <version>${describe.tag.version.next}</version>
    </ref>

    <ref type="tag">
      <pattern><![CDATA[v(?<version>.*)]]></pattern>
      <version>${ref.version}</version>
    </ref>

  </refs>

  <rev>
    <version>${commit}</version>
  </rev>

</configuration>
